import { google } from "googleapis"

import { jwtDecode } from "jwt-decode";

const token : any = process.env.CREDENTIALS ? process.env.CREDENTIALS : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoic2VydmljZV9hY2NvdW50IiwicHJvamVjdF9pZCI6InVzLXByb2plY3QtYXBpIiwicHJpdmF0ZV9rZXlfaWQiOiJkY2VhZTM4MDhkOWFhMGFkMmVmNmYyYjVmMjExYzQ0NTVkZmZmOTE2IiwicHJpdmF0ZV9rZXkiOiItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRREhOYUdIOW9lZmNQSzZcbmd0cjI5TmZJYWorWHZRdXJUSUx4L3Vpclp2cUpsOVFWeVNjZnRwWTJXV0ljMk9YdlF1Vkt5d0l3QXBDV0tpYmdcbkdVN0xETkFoamtSM2tnbEVMMzRYalQ3MkFMZWJnYlN3YVJDWUczUFcxZldoVHl0RHAxUHFIYktsZkExcHpzRUZcbnhIQjFyOUh2MkljbEdRZzZFeEQ1SXdTbzlpRnVOdEFadlA4V1ZxMkFzZU9zWlhRaHJreTJtNGZEYnBCVEtjM3lcblUxZ252TUVMaFBrbTVnd0RsYmtoOS9aellnMGNWTWRVQjkrNm9ESk1nU3U3NGdnQ1Q1R2ZJZGk4cjN4QmFwWEpcbjVtOHNBM3dNSU44RDNUQ0lBNlR6RXdxYXdHYnlmQ25OWGhla1cvZS9kdnNBK0dtSDZXYXpJekpscTJjc2dYQVpcbjFTcnl2UEVsQWdNQkFBRUNnZ0VBSVNBV0tPOXg3RzJoOHlrMHczbUIwem4xc3FQMUo0b3N3UlJYK0w2Q1BUU0JcbnlCQ2ZvSnFpUGszZExucFR1OVkySGhxRlZkbnJWSWtVVjFIbUJBWXdxcy9ISzFIZG1CakVvU0p6M0lEUWh6dUpcbmdnY3FndnlYcGRzRXdnclI0U2xYSHhoS24xRnlRb3ltbExDdVdhZC9vNkF3RXRkbmdvNnVsUnNCV0o0Ni8ySXpcblMvOW5HNFVxRGdPRHYrN0RFRTIwNkxoWk1GS1liR1A2Um1qSkR5Y2REcHNEOEQzMEsvSTM2N0tjR3g0RTdMQ25cbkYrWlY5aDJYbUdVU2RZTkZLbHQrUXEyQW0xZXRNS3BsQWNiWGVRSDhDekxLMlYvYkVFT3JZeGptZkhCZ0J6VEJcbjh5RS94MkZlbG5FZXlzenUvTlJRb2cwM1ZrS2svU1RlK2tOOTA4cVg4UUtCZ1FEclc1ajBTcEYrK2M1alJBcy9cbm5vTm1BWVkyN0VRMzhQWUlrUm95Qm00NG8yWHFhaUZ6SVNsampCVHY3YThGQllQc3NMV21HTGpMSHhpWXYvWUhcbkRlWnNZckx5SS9SOTV0VEFzZkZxQlNrOVFiUEZjRUUyODRsVkwydGdNbHVBL2pkZHlVMGY5YkV2SEhuUmo3aHFcbnRQYndzS0hrakl4K0tYYmdicG41OEpiOVVRS0JnUURZcm1pb1BDeXhodEtMN09VSm5EaG8wZ0dwYU55NWxBdjVcbkpTR3hueU43QVhzdXhlNlliY0hjMU44ZjdDdWZRdGVaNEsvOHVKL1pvRkt0a3ZEU010Y214VTNCQ0RsbmV1eTFcbnl5YVRHQ1hxSyttRGNtOWZaN2pHMVpicUlCRitjZFZwQ0cvVG9GV0dDYnBwanFyUitxNVpkYUh4RTVXcDNlODdcbmVzSVJ1cTh4bFFLQmdHcVEzTjZ2N05VYmN2SExXM1NBNTJvR2dxalhyY1BPblBnZ0MwWmZWd1RhSjBsT3FMcWlcblowVWxwazFFeDV4MGRObDA0YXJGUXRibHk1Tk9SNjNHQTNGTDkwNWdMVkhjZExTVFhZWHR0RkNDTVUzU21CU3pcbmpKay9rVlRMT0ZkZHc5LzVSNnlTNkprMlFZbzdrdnJ0MlduOThDKzEyOTg4RXhGbnd0eENyWHNoQW9HQWRZOWlcbjN1d08vNTU3ZTBsakZxeTRlajUrZ2xDUGVPeFc5cXpycy9mNGd4TlJweFhpbHJidCtJZFNLM3F5VEMweTFwenVcblBycFlsL1dCQmdWMFBVY3lMaW5jUHIvY2pVVkhTbmJYRGZXTEZKc1FqYTIzdVZhSURQRHplVUUrM0pDY1Rla3lcbjZ1blJuUENJUUI4VWxPcGlUODBmdUxGOGdQWVZodnJhY2s0TUlXVUNnWUJUUzJXaXFZaThTRmZCaDhQMlNsZHFcblRmWEF0Tmd5Rm9ycE45K1NxbmJGNWZhY0lUajhob2JjWWpUbWNpa2tMWVhMUG9FbWtKYzNKUHNFZXJoSS81U1VcbnpqY0l4QWVaQzcxZ3JnMGZFUGxLNGVxNGJDempZODNqY2tvaHhUL1M1bktYdUc4cEtuRWZFRTdaYnRPNGFxVlVcbjFVVDhjU3Z2WkdEKzhJZkhWOThiclE9PVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwiY2xpZW50X2VtYWlsIjoiZHJmb3JldmVydXNAdXMtcHJvamVjdC1hcGkuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJjbGllbnRfaWQiOiIxMDY0NDU2NDUxNDc1MTYxNDgyMTkiLCJhdXRoX3VyaSI6Imh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwidG9rZW5fdXJpIjoiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLCJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLCJjbGllbnRfeDUwOV9jZXJ0X3VybCI6Imh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZHJmb3JldmVydXMlNDB1cy1wcm9qZWN0LWFwaS5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsInVuaXZlcnNlX2RvbWFpbiI6Imdvb2dsZWFwaXMuY29tIn0.EIW4l6Jq9Zfr6ms1_IgHzNWdN0W0QX2h1TFklHGmtcQ";
const decoded = jwtDecode(token);

const credentials = JSON.parse(JSON.stringify(decoded))
// import credentials from "./credentials.json"

// authenticates the service account to be used in this context
const auth = new google.auth.GoogleAuth({
    // your credentials to authenticate
    // keyFile: process.cwd() + "/app/credentials.json",
    credentials: credentials,
    // the actions you are permissed to perform using this API, in this case
    // all CRUD operations are permissed, check out
    // [ https://developers.google.com/drive/api/guides/api-specific-auth ]
    // for more advice on scopes
    scopes: ["https://www.googleapis.com/auth/drive"],
  })

export const getData = async () => {
  // allows you to use drive API methods e.g. listing files, creating files.
  const drive = google.drive({ version: "v3", auth })
  try {
    const res = await drive.files.list()
    const files = res.data.files

    return files?.toSorted()
  } catch (error: any) {
    console.error("Error fetching files:", error.message)
    return null
  }
}